#!/usr/bin/env python3
"""
YouTube Selenium login — opens Firefox, waits for the user to sign in,
then exports cookies in Netscape format for yt-dlp.

Usage:
  python3 yt_login.py <cookie_output_path>

Exits with code 0 on success, 1 on failure.
Writes a single JSON status line to stdout:
  {"ok": true,  "message": "..."}
  {"ok": false, "error":   "..."}
"""

import json
import sys
import time
import os

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"ok": False, "error": "Usage: yt_login.py <cookie_path>"}))
        sys.exit(1)

    cookie_path = sys.argv[1]

    try:
        from selenium import webdriver
        from selenium.webdriver.firefox.options import Options
        from selenium.webdriver.firefox.service import Service
        from selenium.webdriver.common.by import By
    except ImportError as e:
        print(json.dumps({"ok": False, "error": f"selenium not installed: {e}"}))
        sys.exit(1)

    options = Options()
    # Non-headless so user can interact
    options.add_argument("--width=1100")
    options.add_argument("--height=800")
    # Disable automation flags that YouTube detects
    options.set_preference("dom.webdriver.enabled", False)
    options.set_preference("useAutomationExtension", False)

    geckodriver = os.environ.get("GECKODRIVER_PATH", "geckodriver")

    try:
        service = Service(geckodriver, log_path=os.devnull)
        driver  = webdriver.Firefox(service=service, options=options)
    except Exception as e:
        print(json.dumps({"ok": False, "error": f"Failed to launch Firefox: {e}"}))
        sys.exit(1)

    try:
        driver.get("https://accounts.google.com/signin/v2/identifier?service=youtube&hl=en")
        driver.execute_script("Object.defineProperty(navigator,'webdriver',{get:()=>undefined})")

        print(json.dumps({"ok": True, "message": "browser_opened",
                          "hint": "Sign in to your Google account, then click 'Capture Cookies' in the app."}),
              flush=True)

        # Poll until the user is signed in (YouTube account avatar appears)
        # or until the browser is closed
        TIMEOUT = 300  # 5 minutes
        start   = time.time()
        signed_in = False

        while time.time() - start < TIMEOUT:
            try:
                url = driver.current_url
            except Exception:
                # Browser was closed by user
                break

            # Detect successful YouTube login — avatar menu button present
            if "youtube.com" in url:
                try:
                    avatars = driver.find_elements(By.CSS_SELECTOR,
                        "button#avatar-btn, yt-img-shadow#avatar-image, "
                        "button[aria-label*='Account'], #avatar-btn")
                    if avatars:
                        signed_in = True
                        break
                except Exception:
                    pass

            # Also check if still on Google accounts page and logged in
            if "myaccount.google.com" in url or "youtube.com/feed" in url:
                signed_in = True
                break

            time.sleep(2)

        if not signed_in:
            # Still try to export whatever cookies we have
            pass

        # Navigate to YouTube to ensure all YT cookies are set
        try:
            if "youtube.com" not in driver.current_url:
                driver.get("https://www.youtube.com")
                time.sleep(3)
        except Exception:
            pass

        # Export cookies in Netscape format for yt-dlp
        try:
            cookies = driver.get_cookies()
        except Exception:
            cookies = []

        if not cookies:
            print(json.dumps({"ok": False, "error": "No cookies captured — were you signed in?"}))
            sys.exit(1)

        # Write Netscape HTTP Cookie File format
        lines = ["# Netscape HTTP Cookie File", "# Generated by yt-login.py", ""]
        yt_count = 0
        for c in cookies:
            domain   = c.get("domain", "")
            flag     = "TRUE" if domain.startswith(".") else "FALSE"
            path_    = c.get("path", "/")
            secure   = "TRUE" if c.get("secure", False) else "FALSE"
            expires  = int(c.get("expiry", 0))
            name     = c.get("name", "")
            value    = c.get("value", "")
            if not name:
                continue
            lines.append(f"{domain}\t{flag}\t{path_}\t{secure}\t{expires}\t{name}\t{value}")
            if "youtube.com" in domain or "google.com" in domain:
                yt_count += 1

        with open(cookie_path, "w") as f:
            f.write("\n".join(lines) + "\n")

        if yt_count == 0:
            print(json.dumps({"ok": False,
                              "error": "Cookies saved but no YouTube/Google cookies found. Make sure you signed in."}))
            sys.exit(1)

        print(json.dumps({"ok": True, "message": f"Captured {len(cookies)} cookies ({yt_count} YouTube/Google)"}))
        sys.exit(0)

    except Exception as e:
        print(json.dumps({"ok": False, "error": str(e)}))
        sys.exit(1)

    finally:
        try:
            driver.quit()
        except Exception:
            pass


if __name__ == "__main__":
    main()
